services:
  builder:
    profiles: [ "builder" ]
    image: modxo-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/dev
    volumes:
      - .:/home/dev
    environment:
      - MODXO_PINOUT
      - CLEAN
      - BUILD_TYPE
    command: [ "/home/dev/tools/dockerbuild.sh" ]
  bios2uf2:
    profiles: [ "bios2uf2" ]
    image: modxo-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/dev
    volumes:
      - .:/home/dev
    command: [ "python", "tools/flashbin_to_uf2.py", "--output-dir", "/home/dev/out", "bios.bin", "bios/*.bin" ]
