#pragma once
#include <modxo.h>
#include <stdint.h>


#define SDCARD_COMMAND_NONE 0

// IO Write

#define SDCARD_COMMAND_REQUEST_DIR_LIST_REFRESH 1
#define SDCARD_COMMAND_REQUEST_FILE_READ_CHUNK 2
#define SDCARD_COMMAND_REQUEST_CWD_TO_ROOT 3

#define SDCARD_COMMAND_SET_LIST_ENTRY_INDEX 32
#define SDCARD_COMMAND_SET_LIST_NAME_INDEX 33
#define SDCARD_COMMAND_SET_FILE_CHUNK_INDEX_LO 34
#define SDCARD_COMMAND_SET_FILE_CHUNK_INDEX_HI 35
#define SDCARD_COMMAND_SET_FILE_CHUNK_READ_INDEX 36
#define SDCARD_COMMAND_REQUEST_CWD_PARENT 37
#define SDCARD_COMMAND_REQUEST_CWD_ENTER_SELECTED 38

// IO Read — directory listing (current CWD)

#define SDCARD_COMMAND_GET_RESPONSE_LIST_READY 64
#define SDCARD_COMMAND_GET_RESPONSE_LIST_COUNT 65
#define SDCARD_COMMAND_GET_RESPONSE_LIST_ENTRY_ID 66
#define SDCARD_COMMAND_GET_RESPONSE_LIST_ENTRY_FLAGS 67
#define SDCARD_COMMAND_GET_RESPONSE_LIST_NAME_LENGTH 68
#define SDCARD_COMMAND_GET_RESPONSE_LIST_NAME_BYTE 69

// IO Read — file data (chunk up to SDCARD_FILE_CHUNK_SIZE bytes, file up to SDCARD_FILE_MAX_SIZE)

#define SDCARD_COMMAND_GET_RESPONSE_FILE_OP_READY 70 
#define SDCARD_COMMAND_GET_RESPONSE_FILE_CHUNK_LENGTH_LO 71
#define SDCARD_COMMAND_GET_RESPONSE_FILE_CHUNK_LENGTH_HI 72
#define SDCARD_COMMAND_GET_RESPONSE_FILE_CHUNK_BYTE 73 
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B0 74 
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B1 75
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B2 76
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B3 77
#define SDCARD_COMMAND_GET_RESPONSE_FILE_READ_RESULT 78
#define SDCARD_COMMAND_GET_RESPONSE_CWD_RESULT 79

#define SDCARD_LIST_FLAG_DIRECTORY 0x01

#define SDCARD_CWD_PATH_MAX 255

#define SDCARD_CWD_RESULT_OK 0
#define SDCARD_CWD_RESULT_BAD_INDEX 1
#define SDCARD_CWD_RESULT_NOT_DIRECTORY 2
#define SDCARD_CWD_RESULT_PATH_TOO_LONG 3
#define SDCARD_CWD_RESULT_AT_ROOT 4

#define SDCARD_FILE_CHUNK_SIZE 1024
#define SDCARD_FILE_MAX_SIZE (32u * 1024u * 1024u)

#define SDCARD_FILE_READ_RESULT_IDLE 0 
#define SDCARD_FILE_READ_RESULT_OK 1
#define SDCARD_FILE_READ_RESULT_ERROR 2
#define SDCARD_FILE_READ_RESULT_IS_DIRECTORY 3
#define SDCARD_FILE_READ_RESULT_BAD_INDEX 4

extern MODXO_TASK sdcard_hdlr;
