#pragma once
#include <modxo.h>
#include <stdint.h>

// Expansion Packet Protocol (sdcard)

#define SDCARD_COMMAND_NONE 0

// IO Write

/* Scan SD root ("0:/"): command reg then data write queues refresh on core0. */
#define SDCARD_COMMAND_REQUEST_ROOT_LIST_REFRESH 1
/* Open root file at last SET_ROOT_LIST_ENTRY_INDEX, read up to SDCARD_FILE_CHUNK_SIZE at offset (SET_FILE_OFFSET_B0..B3), then close. One CMD write queues. Async. */
#define SDCARD_COMMAND_REQUEST_FILE_READ_CHUNK 2

#define SDCARD_COMMAND_SET_ROOT_LIST_ENTRY_INDEX 32
#define SDCARD_COMMAND_SET_ROOT_LIST_NAME_INDEX 33
/* Little-endian offset for next READ_CHUNK (max 16 MiB - 1). Set B0..B3, then READ_CHUNK (uses entry index from SET_ROOT_LIST_ENTRY_INDEX). */
#define SDCARD_COMMAND_SET_FILE_OFFSET_B0 34
#define SDCARD_COMMAND_SET_FILE_OFFSET_B1 35
#define SDCARD_COMMAND_SET_FILE_OFFSET_B2 36
#define SDCARD_COMMAND_SET_FILE_OFFSET_B3 37
#define SDCARD_COMMAND_SET_FILE_CHUNK_READ_INDEX 39

// IO Read — root listing

#define SDCARD_COMMAND_GET_RESPONSE_ROOT_LIST_READY 64
#define SDCARD_COMMAND_GET_RESPONSE_ROOT_LIST_COUNT 65
#define SDCARD_COMMAND_GET_RESPONSE_ROOT_LIST_ENTRY_ID 66
#define SDCARD_COMMAND_GET_RESPONSE_ROOT_LIST_ENTRY_FLAGS 67
#define SDCARD_COMMAND_GET_RESPONSE_ROOT_LIST_NAME_LENGTH 68
#define SDCARD_COMMAND_GET_RESPONSE_ROOT_LIST_NAME_BYTE 69

// IO Read — file data (chunk up to SDCARD_FILE_CHUNK_SIZE bytes, file up to SDCARD_FILE_MAX_SIZE)

#define SDCARD_COMMAND_GET_RESPONSE_FILE_OP_READY 70 // 1 = chunk read request finished
#define SDCARD_COMMAND_GET_RESPONSE_FILE_CHUNK_LENGTH_LO 71
#define SDCARD_COMMAND_GET_RESPONSE_FILE_CHUNK_LENGTH_HI 72
#define SDCARD_COMMAND_GET_RESPONSE_FILE_CHUNK_BYTE 73 // increments chunk read index
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B0 74 // LE, from last successful READ_CHUNK (file closed after read)
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B1 75
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B2 76
#define SDCARD_COMMAND_GET_RESPONSE_FILE_SIZE_B3 77
/* Last READ_CHUNK outcome; required to tell errors from size=0/chunk=0 (empty file, EOF). */
#define SDCARD_COMMAND_GET_RESPONSE_FILE_READ_RESULT 78

#define SDCARD_ROOT_FLAG_DIRECTORY 0x01

#define SDCARD_FILE_CHUNK_SIZE 1024
#define SDCARD_FILE_MAX_SIZE (16u * 1024u * 1024u)

#define SDCARD_FILE_READ_RESULT_IDLE 0 // no completed read yet, or cleared after root refresh
#define SDCARD_FILE_READ_RESULT_OK 1
#define SDCARD_FILE_READ_RESULT_ERROR 2
#define SDCARD_FILE_READ_RESULT_IS_DIRECTORY 3
#define SDCARD_FILE_READ_RESULT_TOO_LARGE 4
#define SDCARD_FILE_READ_RESULT_BAD_INDEX 5

#define SDCARD_COMMAND_GET_RESPONSE_FILE_OPEN_STATUS SDCARD_COMMAND_GET_RESPONSE_FILE_READ_RESULT
#define SDCARD_FILE_STATUS_CLOSED SDCARD_FILE_READ_RESULT_IDLE
#define SDCARD_FILE_STATUS_OK SDCARD_FILE_READ_RESULT_OK
#define SDCARD_FILE_STATUS_OPEN SDCARD_FILE_READ_RESULT_OK
#define SDCARD_FILE_STATUS_ERROR SDCARD_FILE_READ_RESULT_ERROR
#define SDCARD_FILE_STATUS_IS_DIRECTORY SDCARD_FILE_READ_RESULT_IS_DIRECTORY
#define SDCARD_FILE_STATUS_TOO_LARGE SDCARD_FILE_READ_RESULT_TOO_LARGE
#define SDCARD_FILE_STATUS_BAD_INDEX SDCARD_FILE_READ_RESULT_BAD_INDEX

extern MODXO_TASK sdcard_hdlr;
