#LPC GPIOs
set(GPIOS STRING 123)
set(LPC_LAD_START 0)
set(LPC_CLK       4)
set(LPC_LFRAME    5)
set(GPIO_D0       6)
set(LPC_RESET     7)
set(LPC_ON        8)
set(LPC_SERIRQ    28)

set(LCD_PORT_I2C_ENABLE false)
set(LCD_PORT_SPI_ENABLE false)

#SPI/ALT SD_CARD GPIOs
set(SD_CARD_SPI_ENABLE true)
set(SD_CARD_SPI_INST spi1)
set(SD_CARD_SPI_CSN 9)
set(SD_CARD_SPI_CLK 14)
set(SD_CARD_SPI_MISO 12)
set(SD_CARD_SPI_MOSI 15)
set(ALT_SPI_CSN 18)

#UART GPIOs
set(UART_ENABLE true)
set(UART_INST uart0)
set(UART_TX 16)
set(UART_RX 17)

#RGB LED GPIOs
set(LED_STRIP1_PWR 31)
set(LED_STRIP1 23)

#EXPANSION PORT
set(EXPANSION_PORT_I2C_INST i2c0)
set(EXPANSION_PORT_I2C_SDA 20)
set(EXPANSION_PORT_I2C_SCL 21)

#STATUS LED
set(LED_STATUS_ON_LEVEL 1)
set(LED_STATUS_OFF_LEVEL 0)
set(LED_STATUS_PIN 25)

#LED STRIP PIXEL FORMAT
set(RGB_STATUS_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP1_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP2_PIXEL_FORMAT PIXEL_FORMAT_GRB)

#FRONT PANEL
set(FRONT_PANEL_EJECT 29)
set(BFRONT_PANEL_POWER4 22)

#X3 LOGO
set(X3_LOGO_RED 18)
set(X3_LOGO_BLUE 19)

#MODXO VARIANT
set(MODXO_VARIANT MODXO_VARIANT_R3MUX)
