#LPC GPIOs
set(GPIOS STRING 123)
set(LPC_LAD_START 1)
set(LPC_CLK       5)
set(LPC_LFRAME    6)
set(GPIO_D0       7)
set(LPC_RESET     8)
set(LPC_ON        9)
set(SERIRQ        10)

#PSRAM
set(PSRAM_CS1 0)
set(PSRAM_ID  51) #PSRAM ID
set(PSRAM_MAX_SELECT_FS64 125000000) #Max frequency for PSRAM in FS64 mode
set(PSRAM_MIN_DESELECT_FS 50000000) 
set(PSRAM_MAX_SCK_HZ 109000000)


#LCD_PORT GPIOs
set(LCD_PORT_I2C_ENABLE true)
set(LCD_PORT_I2C_INST i2c1)
set(LCD_PORT_I2C_SDA 18)
set(LCD_PORT_I2C_SCL 19)

set(LCD_PORT_SPI_ENABLE true)
set(LCD_PORT_SPI_INST spi0)
set(LCD_PORT_SPI_MOSI ${LCD_PORT_I2C_SCL})
set(LCD_PORT_SPI_CLK  ${LCD_PORT_I2C_SDA})
set(LCD_PORT_SPI_CSN1  24)
set(LCD_PORT_SPI_CSN2  26)

#SD_CARD GPIOs
set(SD_CARD_SPI_ENABLE true)
set(SD_CARD_SPI_INST spi1)
set(SD_CARD_SPI_CSN 13)
set(SD_CARD_SPI_CLK 14)
set(SD_CARD_SPI_MISO 12)
set(SD_CARD_SPI_MOSI 15)

#UART GPIOs
set(UART_ENABLE true)
set(UART_INST uart0)
set(UART_TX 16)
set(UART_RX 17)

#RGB LED GPIOs
set(LED_STRIP1_PWR 31)
set(LED_STRIP1 23)

#EXPANSION PORT
set(EXPANSION_PORT_I2C_INST i2c0)
set(EXPANSION_PORT_I2C_SDA 20)
set(EXPANSION_PORT_I2C_SCL 21)

#STATUS LED
set(LED_STATUS_ON_LEVEL 1)
set(LED_STATUS_OFF_LEVEL 0)
set(LED_STATUS_PIN 25)

#LED STRIP PIXEL FORMAT
set(RGB_STATUS_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP1_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP2_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP3_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP4_PIXEL_FORMAT PIXEL_FORMAT_GRB)

#MODXO VARIANT
set(MODXO_VARIANT MODXO_VARIANT_WEACT)

set(PICO_BOARD pico2)
set(PICO_PLATFORM rp2350)
set(PICO_RP2350_A2_SUPPORTED 0)