#LPC GPIOs
set(GPIOS STRING 123)
set(LPC_LAD_START 26)
set(LPC_CLK       0)
set(LPC_LFRAME    1)
set(GPIO_D0       2)
set(LPC_RESET     3)
set(LPC_ON        4)

#LCD_PORT GPIOs
set(LCD_PORT_I2C_ENABLE false)
set(LCD_PORT_I2C_INST i2c0)
set(LCD_PORT_I2C_SDA 31)
set(LCD_PORT_I2C_SCL 31)

set(LCD_PORT_SPI_ENABLE false)
set(LCD_PORT_SPI_INST spi1)
set(LCD_PORT_SPI_MOSI ${LCD_PORT_I2C_SCL})
set(LCD_PORT_SPI_CLK  ${LCD_PORT_I2C_SDA})
set(LCD_PORT_SPI_CSN1  31)
set(LCD_PORT_SPI_CSN2  31)

#SD_CARD GPIOs
set(SD_CARD_SPI_ENABLE false)
set(SD_CARD_SPI_INST spi0) # Discarded pin
set(SD_CARD_SPI_MISO 31)   # Discarded pin
set(SD_CARD_SPI_CSN  31)   # Discarded pin
set(SD_CARD_SPI_CLK  31)   # Discarded pin
set(SD_CARD_SPI_MOSI 31)   # Discarded pin

#UART GPIOs
set(UART_ENABLE false)
set(UART_INST uart0)
set(UART_TX 31)            # Discarded pin
set(UART_RX 31)            # Discarded pin

#RGB LED GPIOs
set(LED_STRIP1_PWR 11)
set(LED_STRIP1 12)

#EXPANSION PORT
set(EXPANSION_PORT_I2C_INST i2c1)
set(EXPANSION_PORT_I2C_SDA 6)
set(EXPANSION_PORT_I2C_SCL 7)

#STATUS LED
set(LED_STATUS_ON_LEVEL 0)
set(LED_STATUS_OFF_LEVEL 1)
set(LED_STATUS_PIN 25)

#LED STRIP PIXEL FORMAT
set(RGB_STATUS_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP1_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP2_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP3_PIXEL_FORMAT PIXEL_FORMAT_GRB)
set(STRIP4_PIXEL_FORMAT PIXEL_FORMAT_GRB)

#MODXO VARIANT
set(MODXO_VARIANT MODXO_VARIANT_XIAO_RP2040)

add_compile_definitions(PICO_FLASH_SPI_CLKDIV=4)
